### ISSUE TITLE
Error: All sentinels are unreachable. Retrying from scratch after 10ms ....but crashes

### ISSUE THREAD

**Issue by kmcrawford** [apollographql/apollo-utils#201]
I have a load balanced redis sentinels running in kuberenetes, however every hour I get this error below  and this "warning" is causing my application to crash.  I am still investigating, why this code thinks they are unavailable (which they aren't), but is there a way to catch this application as it looks like `ioredis` wants to retry in 10ms.

 

const redis = new Redis({
      sentinels: [{ host: process.env.REDIS_HOST, port: 26379 }],
      name: 'mymaster',
    });
    const keyvRedis = new KeyvRedis(redis);
    cache = new KeyvAdapter(new Keyv({ store: keyvRedis }));

```
/node_modules/standard-as-callback/built/index.js:6
        throw e;
Error: All sentinels are unreachable. Retrying from scratch after 10ms.
    at SentinelConnector.<anonymous> (/node_modules/ioredis/built/connectors/SentinelConnector/index.js:73:31)
    at Generator.next (<anonymous>)
    at /node_modules/ioredis/built/connectors/SentinelConnector/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/ioredis/built/connectors/SentinelConnector/index.js:4:12)
    at connectToNext (/node_modules/ioredis/built/connectors/SentinelConnector/index.js:59:37)
    at SentinelConnector.connect (/node_modules/ioredis/built/connectors/SentinelConnector/index.js:128:16)
    at /node_modules/ioredis/built/redis/index.js:292:55
    at new Promise (<anonymous>)
    at Redis.connect (/node_modules/ioredis/built/redis/index.js:265:21)
Emitted 'error' event on Keyv instance at:
    at KeyvRedis.<anonymous> (/node_modules/keyv/src/index.js:61:46)
    at KeyvRedis.emit (node:events:390:28)
    at Redis.<anonymous> (/node_modules/@keyv/redis/src/index.js:18:40)
    at Redis.emit (node:events:390:28)
    at Redis.silentEmit (/node_modules/ioredis/built/redis/index.js:553:26)
    at /node_modules/ioredis/built/redis/index.js:297:23
    at tryCatcher (/node_modules/standard-as-callback/built/utils.js:12:23)
    at /node_modules/standard-as-callback/built/index.js:33:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by trevor-scheer** [comment]
@kmcrawford sounds like an `ioredis` issue. Can you provide a reproduction that demonstrates how this issue is a `keyvadapter` problem? Will reopen with a runnable reproduction.

**Comment by kmcrawford** [comment]
@trevor-scheer you can see from the stack trace that `keyvadpter` is not handling the error correctly. I provided sample code in the ticket description.

**Comment by trevor-scheer** [comment]
@kmcrawford i see `keyv`, `@keyv/redis`, and `ioredis` in the stack trace. I don't see `@apollo/utils.keyvadapter`. It seems like the error that is happening should be correctly handled in your redis or keyv instances, not by the adapter.

A snippet is not a reproduction. I need to be able to see the error happen myself in order to debug, so something that I can clone and run or demonstrating the problem through a failing test case in this repo would be sufficient.

**Comment by trevor-scheer** [comment]
Assume `KeyvAdapter` were not part of this equation, since it's really just a wrapper / translation layer.

`Keyv` reemits an error which was emitted by `ioredis`.
https://github.com/jaredwray/keyv/blob/6b61df7c2f9e705d68b474a369b95007abf637a3/packages/keyv/src/index.js#L61

If `KeyvAdapter` was not here, you would need to handle the error. The same applies with it present, i.e. the adapter has no opinion on how you choose to handle those errors.

Example of handling errors emitted by `Keyv` here:
https://github.com/jaredwray/keyv/tree/main/packages/keyv#usage

Implemented within your snippet:
```ts
const redis = new Redis({
sentinels: [{ host: process.env.REDIS_HOST, port: 26379 }],
name: 'mymaster',
});
const keyvRedis = new KeyvRedis(redis);
keyvRedis.on('error', (error) => {
  console.log(error);
  // ...handle the error as you see fit
});
cache = new KeyvAdapter(new Keyv({ store: keyvRedis }));
```
